'use strict'

/**
 * ADMIN USER STATUS
 */
const ADMIN_USER_STATUS_ACTIVE = 1 ;
const ADMIN_USER_STATUS_NOT_ACTIVE = 0;

/**
 * USER STATUS
 */
const USER_STATUS_ACTIVE = 1 ;
const USER_STATUS_NOT_ACTIVE = 0;


module.exports = {USER_STATUS_ACTIVE ,USER_STATUS_NOT_ACTIVE ,ADMIN_USER_STATUS_ACTIVE ,ADMIN_USER_STATUS_NOT_ACTIVE }